name: base
channels:
  - defaults
dependencies:
  - conda
  - python=3.8
  - numpy
  - console_shortcut
  - conda-env
  - conda-build
  - conda-verify
  - _ipyw_jlab_nb_ext_conf
  - matplotlib
  - scikit-learn
  - tensorflow

